### ISSUE TITLE
adding a client implementation

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#158]
@drmingdrmer 

I would consider adding a client implementation as well since "all communication has to go through the leader" and "it is the clients responsibility to send requests to the leader". That is, show a simple client implementation that handles `ForwardToLeader` errors.

I'm very happy that you put the demo together :heart:. I think it'll help a lot of people. In particular using HTTP endpoints instead of tonic gRPC will make it easier to follow when you're just getting started.

_Originally posted by @MikaelCall in https://github.com/datafuselabs/openraft/issues/155#issuecomment-1028881580_

**Comment by ppamorim** [comment]
@drmingdrmer @MikaelCall I successfully sorted that by doing this: https://github.com/ppamorim/openraft/blob/example/example-raft-kv/src/network/api.rs#L39-L72

**Comment by MikaelCall** [comment]
> 

Like all interesting questions the answer is "it depends" ...

* Yes. The implementation pointed to is convenient and kind of solves the problem in practice. I think there is a theoretical risk of an infinite recursion for unlikely failure scenarios that have to be considered (cf metasrv in the databend repo).
* My main purpose with suggesting a client implementation was clarity and being explicit.
* In practice, handling this on the client side can be more efficient since if the client contacts a node that is not the leader and that node forwards to the leader we have to pay for the node to leader request each time. If the client gets an error and updates its belief of who's the leader that extra cost goes away for all future requests which IMHO is much better.

I think that our outlined solutions are not mutually exclusive. I just wanted to bring your attention to more "interesting aspects" of the original question.
