### ISSUE TITLE
Consider refactoring Snapshot type bound.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#209]
This interface is geared toward small file-based snapshots. However, not all snapshots can
be easily represented as a file. Probably a more generic interface will be needed to address
also other needs.

https://github.com/datafuselabs/openraft/blob/46644c8409c7dff627c991cc65849507ad5265b3/openraft/src/storage.rs#L147-L159

**Comment by fredfortier** [comment]
I'd like to understand this a bit better. I could perhaps submit a PR to suggesting an implementation. My snapshots are actually large and not stored as files. The interface works afaik, but I do experience issues like #235 that may be related to these snapshot assumptions.

**Comment by drmingdrmer** [comment]
The API forces user to implement a snapshot in a byte-stream way.
IMHO, a snapshot would be better to be a stream of a user-defined data type.

And incremental snapshot replication may be useful.

**Comment by schreter** [comment]
@fredfortier We also have a relatively complex snapshot that is not file based. Basically, it is a set of pages to transfer with some meta information regarding page location (since the pages may cross-reference themselves). This needs to be materialized at the remote side.

Although it is surely possible to access such a snapshot using a byte stream, it's quite complex to provide a reliable working random-access implementation to it. It would be simpler to handle it in a different way, with records with associated metadata.

I even though of sending a small snapshot info (~2KB) to the follower via the existing snapshot interface and then actively request data belonging to this snapshot from the leader as needed. I still don't have a concrete idea how to cut the API the best to handle all possible use cases.

**Comment by zach-schoenberger** [comment]
@drmingdrmer would it make sense to make `Snapshot`'s bounds be `futures_core::Stream Send + Unpin + 'static` instead of `AsyncRead + AsyncSeek + Send + Unpin + 'static` for `RaftSnapshotBuilder`? I was going through looking how to implement the snapshoting in my project and ran into an issue with the current trait bounds. Mainly that `AsyncSeek` isn't really an option for me. And looking at the snapshot code i'm not really sure why it's needed. Any insight there would be great!

**Comment by drmingdrmer** [comment]
> @drmingdrmer would it make sense to make `Snapshot`'s bounds be `futures_core::Stream + Send + Unpin + 'static` instead of `AsyncRead + AsyncSeek + Send + Unpin + 'static` for `RaftSnapshotBuilder`?

Agree. a `Stream` of user-defined data chunks would be better. And it can just be a stream of `Vec<u8>` to simulate an `AsyncRead`.

> I was going through looking how to implement the snapshoting in my project and ran into an issue with the current trait bounds. Mainly that `AsyncSeek` isn't really an option for me. And looking at the snapshot code i'm not really sure why it's needed. Any insight there would be great!

I guess it is a historical reason: the API is derived from etcd-raft in which a snapshot is just a byte stream.

**Comment by zach-schoenberger** [comment]
@drmingdrmer would you mind checking if the approach I took here https://github.com/zach-schoenberger/openraft/tree/snapshot_stream looks good to you? If so I'll finish out updating the tests and examples

**Comment by drmingdrmer** [comment]
> @drmingdrmer would you mind checking if the approach I took here https://github.com/zach-schoenberger/openraft/tree/snapshot_stream looks good to you? If so I'll finish out updating the tests and examples

Thank you for your suggestion.
Can you make it a **draft** PR so that everyone will be able to see the changes clearly online?

**Comment by zach-schoenberger** [comment]
noting here the pr: https://github.com/datafuselabs/openraft/pull/600
