### ISSUE TITLE
Change: RaftStorage: rename: save_vote() to save_ballot()

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#245]

**Comment by schreter** [comment]
> rename: save_vote() to save_ballot()

Why? "Vote" sounds better...

**Comment by drmingdrmer** [comment]
Hmm... to me, **vote** somehow means the voting procedure, between candidates. A ballot is a decision a candidate made about who it voted for.

From Wikipedia https://en.wikipedia.org/wiki/Ballot

> A **ballot** is a device used to cast votes in an election and may be found as a piece of paper or a small ball...
> 
> Each voter uses one **ballot**, and ballots are not shared. ...

And ballot in Paxos is almost equivalent to the tuple of `(term, candidate_node_id)` in raft, and in `openraft`,  the `Vote`:
```rust
pub struct Vote<C: RaftTypeConfig> {
    pub term: u64,
    pub node_id: C::NodeId,
    pub committed: bool,
}
```

> In Paxos, a value is decided when a majority of acceptors have accepted the same **ballot**, consisting of a **ballot** number (aka a view, term, or proposal number) and a value. Paxos ensures that once a value is decided, no different value can be proposed with any greater **ballot** number. It achieves this by requiring proposers in phase 1 of Paxos to learn the greatest accepted **ballot** from a majority of acceptors and to propose the value with the greatest **ballot** number in phase 2.

English is not my native language. If `vote` is good enough for you, let's keep using it.

**Comment by schreter** [comment]
> And ballot in Paxos is almost equivalent to the tuple of (term, candidate_node_id) in raft, and in openraft, the Vote:

Yes. Leslie Lamport talks in his Paxos paper (https://lamport.azurewebsites.net/pubs/lamport-paxos.pdf) about "ballots".

However, Diego Ongaro talks in his Raft paper (https://raft.github.io/raft.pdf) about "votes".

> English is not my native language.

Neither is it mine :-). It's the fourth I learned and probably the third best I can speak (but, professionally, probably the best).

> If vote is good enough for you, let's keep using it.

It is good enough, I think.

Although I agree with you that "more proper" English likely would be a "ballot", "vote for" seems to be used about an order of magnitude more frequently than "cast(ing) a ballot", according to quick Google match count ("casting a ballot" sounds a kind of "old" and/or "snobbish" to me, but that's just my feeling). And, since we are implementing Raft, I'd suggest to keep with the Raft terminology of "vote".

**Comment by drmingdrmer** [comment]
> Although I agree with you that "more proper" English likely would be a "ballot", "vote for" seems to be used about an order of magnitude more frequently than "cast(ing) a ballot", according to quick Google match count

Good. Majority wins.XDDD
