### ISSUE TITLE
`Raft::shutdown()` seems not to work properly

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#373]
First, the experiment description:

I have a (simulated) Raft cluster for testing takeover. This Raft cluster consists of three nodes, where one of them is initially elected as leader. All (simulated) clients now hammer this leader.

After some time, the network connection to the leader is cut off (only in-cluster network, the connection from clients to the leader is still working), which causes a new election under surviving members. A new leader is properly elected. All clients should now start hammering this new leader.

Now my problem is that those clients are stuck in communication with the old leader, which will never answer, since it doesn't get its responses from other cluster members. Therefore, I called `Raft::shutdown()` on the leader, expecting clients to fail with some error message and then reconnect to the new leader (which is already known in the test setup). This also used to work some time ago (before the refactoring moving Raft core out).

Now, it doesn't work anymore, since `Raft::get_core_error()` panics with `no RaftCore error found` (and effectively kills all my clients).

I can easily work around the problem by returning a synthetic error from `Raft::get_core_error()` instead of panicking, which will then propagate the error to the client trying to execute the request and the client then successfully reconnects to the new leader. But, this is just a workaround, real solution is necessary.

I suppose, the real problem lies somewhere in shutdown handling - the target state is set to shut down, but there is no error registered (since it's a clean shutdown). So either the shutdown should register an error to be returned to the client, or the `Raft::get_core_error()` should detect that the node was shut down and return an appropriate error instead of panicking.

Ideas? Fixes?

**Comment by drmingdrmer** [comment]
My hero!

A normal shutdown should also be considered an error and be tracked.

- `Raft.inner.core_error` should be able to store a normal exit state. And it should be renamed to reflect its actual purpose.
- When calling `Raft::shutdown()`, if `Raft.inner.raft_handle` is joined without an error, `Raft.inner.core_error` should be set to `Ok(_)`.
- The error propagation adjustment: RaftCore returns an Ok or Err, and report this state to `tx_metrics` to inform external subscribers; `Raft::shutdown()` or `Raft::get_core_error()` should wait for `Raft.inner.raft_handle` to return the OK or Err then update it to `Raft.inner.core_error`. `Raft::get_core_error()` do not need to check the error stored in 
 `Raft.inner.rx_metrics` any more, since it has to be already stored in `Raft.inner.core_error`.
- Waiting for `Raft.inner.raft_handle` then updating `Raft.inner.core_error` should be atomic, e.g. by holding a mutex. Otherwise `Raft::get_core_error()` may have a chance can not get the result returned from `RaftCore`.
