### ISSUE TITLE
Make `last_log_id` an `Option<LogId>`, or it can not express an uninitialized state

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#49]
https://github.com/datafuselabs/openraft/blob/344d444c4ef84867d2ef09fb58032832b2148fcf/openraft/src/core/mod.rs#L140

**Comment by YangKian** [comment]
Hi~ I have an idea to discuss with you guys, using `Option<LogId>` instead of last_log_id introduces a lot of `unwrap` operations, fortunately, PR #94 adds a return error type for many APIs, so I would like to add a helper function for `RaftCore`: 

```
impl RaftCore {
    fn get_last_log_id(&self) -> Result<LogId, SomeErr>
}
```
use `option.ok_or_else()` to convert `None` to an Err. 

What do you think? Also regarding the error type returned, should I add a new error type or return an existing error? Would like to hear your suggestions! @drmingdrmer @Veeupup

**Comment by YangKian** [comment]
I see, thanks for the advice!
