### ISSUE TITLE
Recommended values for `Config::max_applied_log_to_keep` and `Config::snapshot_policy`

### ISSUE THREAD

**Issue by Gab-Menezes** [datafuselabs/openraft#505]
I was curious about the behaviour when `Config::max_applied_log_to_keep < Config::snapshot_policy` (in this case we start to purge logs before creating a snapshot), which could be a problem since can lead to some possible data loss.
My tests where specially in the case where another node enters the cluster before creating a snapshot and having some logs purged. In this case the Leader notices this problem and generate a new snapshot before sending data to the new node. This can lead to higher downtime since the snapshot is not up and ready to the new node.
As a preemptive solution (to avoid any possible problems) this values should be set as `Config::max_applied_log_to_keep > Config::snapshot_policy` and added at `Config::validate()`.
What do you guys think ?

Note: The current default values for this options can lead to this problems.

**Comment by drmingdrmer** [comment]
> I was curious about the behaviour when `Config::max_applied_log_to_keep < Config::snapshot_policy` (in this case we start to purge logs before creating a snapshot), which could be a problem since can lead to some possible data loss. 

You're right there are problems with such a setting.
But it won't lead to data loss, since the application should have to implement `RaftStorage::apply_to_state_machine()` in a way so that when this method returns, the applied log is already persisted.
The problem only leads to frequent snapshot building, as you mentioned.


> My tests where specially in the case where another node enters the cluster before creating a snapshot and having some logs purged. In this case the Leader notices this problem and generate a new snapshot before sending data to the new node. This can lead to higher downtime since the snapshot is not up and ready to the new node. As a preemptive solution (to avoid any possible problems) this values should be set as `Config::max_applied_log_to_keep > Config::snapshot_policy` and added at `Config::validate()`. What do you guys think ?
> 
> Note: The current default values for this options can lead to this problems.

I noticed this issue too and was planning to change `max_applied_log_to_keep` to `max_in_snapshot_log_to_keep`, and openraft should just simply not to delete any logs that are not in a snapshot. I hope this will be more clear for users.

Thank you so much for informing me about this issue:D

**Comment by Gab-Menezes** [comment]
Since this change was already merged I'm gonna close this one, ty.
