### ISSUE TITLE
Update API trait with GAT

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#604]
https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#whats-in-1650-stable

![image](https://user-images.githubusercontent.com/44069/201254700-637e3a99-4b3e-416f-bed1-c98c15153a6f.png)

**Comment by Xuanwo** [comment]
Hi, this issue has been open for a while. Perhaps we can schedule some actionable tasks to get it started?

**Comment by schreter** [comment]
In fact, in the meantime we can simply use async functions in traits (since 1.75). For single-threaded mode, the `add_async_trait` macro is a no-op and we are using native async fn in trait. @wvwwvwwv implemented that.

For "regular" use, I think there were some concerns regarding `Send`-ability of the generated futures. But you may try to simply remove `async_trait` completely and see what happens. If it "simply works" then it would be the best.

**Comment by schreter** [comment]
@Xuanwo Ah, I just see there is a PR #996 which addresses this by specifying `Send` bounds as needed. So this issue is then moot, we should merge that (provided it works, of course - but it seems like it does :-) and with that #959 is completely done. I.e., this is in a way duplicate of #959 .

**Comment by drmingdrmer** [comment]
Dup of:
- #959 

Fixed in:
- #982 
- #996
