### ISSUE TITLE
Error handling at user space

### ISSUE THREAD

**Issue by Gab-Menezes** [datafuselabs/openraft#634]
**Is your feature request related to a problem? Please describe.**
Sometimes is desirable to know when a problem happens to a node at user space. We can see this problems via logs printed by the application, but it's not possible to take an automatic action (as far as I know).

Suppose the scenario where the we have a 4 node cluster (1 leader, 3 followers), and for some reason one of those 3 followers went down and is no longer reachable by the leader (this is only one example of things that can happen, think about lagging, snapshot installation problems and other potential errors), maybe the Openraft users would like to have a way to be notified of this problems.

Let's take my case as an example: If node went down I would like to remove it via new membership or try to take another action to fix the problem.

**Describe the solution you'd like**
I was thinking of some callback function (or functions, one for each potential problem) that is registered when creating the Raft object. This functions would receive the problematic node as a parameter (in the case of a single function would also receive the problem as an an enum) and return what action should be taken (this last part is no obligatory since the user can decide and take this action inside the function it self, maybe just return what was decided).

This function would be triggered only in the leader node, if there is no leader in the moment we would wait to a new leader to be decided via election an then trigger the function.

**Note**
I don't know if this is possible or the correct way to approach this problem. At some point I needed to do this sort of automation but wasn't able to find (in the docs) or create a way around it.

**Comment by drmingdrmer** [comment]
Usually, `metrics()` is the entry for all raft node monitoring tasks. 

https://github.com/datafuselabs/openraft/blob/2dd81018b54a74d46af6412048b2f057bb35c56e/openraft/src/raft.rs#L776-L778

You can find health information in it:

https://github.com/datafuselabs/openraft/blob/e4b705cabbc417b2ef6569a31b2ba83a71cac41e/openraft/src/metrics/raft_metrics.rs#L16-L59

A maintenance routine can make decisions based on these metrics. But it must do it with caution:

1. A leader can not assure if a node is going wrong and should be removed from the cluster. It may be network issues or even problems with the leader itself.
2. A leader may have already become invalid: there is another new leader with a higher term. Thus a maintenance request(e.g., removing a node) must be rejected by the new leader. Because in a cluster at most only one process can make maintenance decisions.
3. A leader that can decide to remove a node might remove all of the nodes one by one, and finally, it becomes a single-node cluster, which affects system availability. Thus IMHO, a maintenance bot must be responsible for adding a new node when it removes a node.
