### ISSUE TITLE
about add learner

### ISSUE THREAD

**Issue by web3creator** [datafuselabs/openraft#846]
I read the document that the add_leaner function will block until the node completes synchronization, but the actual time is 500ms. How can I implement the add_leaner function to block for an infinite time until the synchronization is completed?

After I execute add learner (because it blocks up to 500ms), and then immediately change the status to voter, will this affect the data synchronization of the cluster? If I have a lot of nodes, because in fact these nodes do not satisfy the voter, at this time Their data has not been synchronized from the leader

**Comment by HHoflittlefish777** [comment]
Hi,I try to express my option.

- I think the timeout setting of 500ms is to prevent add caused by network that prevent synchronization from completing add_learner function has been blocking. However, if you are confident that synchronization will always complete successfully and want to ensure add_learner function blocks indefinitely, and you can remove the timeout setting or set it to a very large value.

- Regarding your second question, changing the state of a node from learner to voter while synchronization is still in progress may result in data loss or inconsistency in the cluster. When a node is added as a learner, it receives updates from the leader but does not participate in the quorum of write operations. If you immediately change the status of a node from learner to voter after adding it, there is a risk that it may not have received updates from all leaders, resulting in data loss or inconsistency.

**Comment by drmingdrmer** [comment]
> I read the document that the add_leaner function will block until the node completes synchronization, but the actual time is 500ms. How can I implement the add_leaner function to block for an infinite time until the synchronization is completed?

The function `Raft::add_learner()` is designed to wait until the newly added learner catches up with the leader, ensuring that the difference in log entries is within the specified threshold of replication lag. The synchronization check required for adding a learner is performed within this function:

https://github.com/datafuselabs/openraft/blob/b0c30acf92e0aab44a7fcb9cd63294febda53fad/openraft/src/raft.rs#L571-L615

If the `Raft::add_learner()` returns earlier than expected, attach the debug level log(run your application with `RUST_LOG=debug`) and let me examine what's going on.

> After I execute add learner (because it blocks up to 500ms), and then immediately change the status to voter, will this affect the data synchronization of the cluster? If I have a lot of nodes, because in fact these nodes do not satisfy the voter, at this time Their data has not been synchronized from the leader

At any time, change-membership operations(such as upgrade a learner to voter) are safe. The only issue is that if the learner has not yet caught up with the leader, change-membership may block for a while before committing the change.

**Comment by web3creator** [comment]
> check_replication_upto_date
https://github.com/datafuselabs/openraft/blob/b0c30acf92e0aab44a7fcb9cd63294febda53fad/openraft/src/raft.rs#L551
Here the argument to the wait function is None, which means that the maximum duration is 500ms，My actual tests are also like this, no matter how much data the leader has, add_leaner will return quickly

**Comment by drmingdrmer** [comment]
> > check_replication_upto_date
> > https://github.com/datafuselabs/openraft/blob/b0c30acf92e0aab44a7fcb9cd63294febda53fad/openraft/src/raft.rs#L551
> > 
> > Here the argument to the wait function is None, which means that the maximum duration is 500ms，My actual tests are also like this, no matter how much data the leader has, add_leaner will return quickly

Oh... my mistake... Let me fix it!
